name: github-release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log
        uses: yashanand1910/standard-release-notes@v1.2.1
        id: get_release_notes
        with:
          changelog_path: ./CHANGELOG.md
          version: ${{ github.ref }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.get_release_notes.outputs.release_notes }}
